# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1525f54574eb3829e29a78f4e91d8c046ab3b2389294bbeedb0755cc8ebb0b4cded2586e58fd0abcbe3a892d974d6db8c526c726e92bc274eb614ba7ba424c57

test:
  secret_key_base: 7a3e948abb4e06e7816417325bbc13feef809fdd000039f72b7584c8cdd40c2f0395c56079e26e0d0b3f65fb40a260b1c21d19296b013b53cb95edec4b5981c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
